import React from 'react';

const Intro = (props) => {
  return (
    <div>
      <h2
        style={{
          textAlign: 'center',
          paddingBottom: 20,
          borderBottom: 'solid 1px white',
        }}>
        S&P 500 Total Returns
      </h2>
      <span style={{ letterSpacing: '2px', lineHeight: '22px' }}>
        The total returns of the S&P 500 index are listed by year. Total returns
        include two components: the return generated by dividends and the return
        generated by price changes in the index. While most individuals focus
        only on the price returns of the index, dividends play an important
        factor in overall investment returns.
      </span>
    </div>
  );
};

export default Intro;
